### alle Ratings
GET http://localhost:3000/all

### Ratings nach ID
GET http://localhost:3000/id/

### Ratings nach category
GET http://localhost:3000/category/City

### Ratings nach rating
GET http://localhost:3000/rating/

### Ratings nach title
GET http://localhost:3000/title/

### Ratings nach description
GET http://localhost:3000/description/

### Ratings nach country
GET http://localhost:3000/country/

### Ratings nach city
GET http://localhost:3000/city/



### Rating hinzufügen
POST http://localhost:3000/add 
Content-Type: application/json

{
    "category": "Stadt",
    "rating": 9,
    "title": "Was der Süden alles zu bieten hat",
    "description": "Augsburg gehört definitiv zu den schönsten Städten Deutschlands",
    "country": "Deutschland",
    "city": "Augsburg"
}


### Eintrag aktualisieren
PUT http://localhost:3000/
Content-Type: application/json

{
    "category": "Stadt",
    "rating": 3,
    "title": "Sieht aus wie am ASB 8",
    "description": "Das Wollhaus gibt der Stadt den Rest! Wusste ja schon dass des schwierig wird hier aber sowas, näh",
    "country": "Deutschland",
    "city": "Heilbronn"
}

### Eventuell zusätzlich
PATCH  http://localhost:3000/
Content-Type: application/json

{
     "rating": 2
}


### Eintrag löschen
DELETE http://localhost:3000/