### alle Ratings
GET http://localhost:3000/all

### Ratings nach Land
GET http://localhost:3000/country/germany

### Ratings nach ID
GET http://localhost:3000/id/645e61178b8c02e9fabb62ee

### Rating hinzufügen
POST http://localhost:3000/add 
Content-Type: application/json

{
    "category": "City",
    "rating": 4,
    "title": "Stadt Stuttgart",
    "description": "Schöne Stadt, man kann viel machen",
    "country": "germany",
    "city": "stuttgart"
}