### alle Car Rentals
GET http://localhost:3003/all

### Car Rentals nach ID
GET http://localhost:3003/id/

### Car Rentals nach pricePerDay
GET http://localhost:3003/priceperday/

### Car Rentals nach brand
GET http://localhost:3003/brand/

### Car Rentals nach model
GET http://localhost:3003/model/

### Car Rentals nach releaseDate
GET http://localhost:3003/releaseDate/
### Car Rentals nach doorQuant
GET http://localhost:3003/doorQuant/

### Car Rentals nach seats
GET http://localhost:3003/seats/

### Rating hinzufügen
POST http://localhost:3003/add 
Content-Type: application/json

{
    "pricePerDay": 340,
    "brand": "Audi",
    "model": "A3",
    "releaseDate": 2017,
    "doorQuant": 5,
    "seats": 5
}


### Eintrag aktualisieren
PUT http://localhost:3003/
Content-Type: application/json

{
    "pricePerDay": 0,
    "brand": "",
    "model": "",
    "releaseDate": 0,
    "doorQuant": 0,
    "seats": 0
}

### Eventuell noch zusätzlich
PATCH  http://localhost:3000/
Content-Type: application/json

{
     "rating": 2
}


### Eintrag löschen
DELETE http://localhost:3003/