### alle Car Rentals
GET http://localhost:3003/all

### Car Rentals nach ID
GET http://localhost:3003/id/646e804307dcdbeb3e289e7e

### Car Rentals nach pricePerDay
GET http://localhost:3003/priceperday/90

### Car Rentals nach brand
GET http://localhost:3003/brand/toy

### Car Rentals nach model
GET http://localhost:3003/model/ya

### Car Rentals nach releaseDate
GET http://localhost:3003/releaseDate/1684970603

### Car Rentals nach doorQuant
GET http://localhost:3003/doorQuant/5

### Car Rentals nach seats
GET http://localhost:3003/seats/3

### Rating hinzufügen
POST http://localhost:3003/add 
Content-Type: application/json

{
    "pricePerDay": 90,
    "brand": "TOYOTA",
    "model": "YARIS",
    "releaseDate": 1684970603,
    "doorQuant": 5,
    "seats": 7
}


### Car Rental aktualisieren
PUT http://localhost:3003/646e804307dcdbeb3e289e7e
Content-Type: application/json

{
    "pricePerDay": 100,
    "brand": "VW",
    "model": "GOLF",
    "releaseDate": 1684970603,
    "doorQuant": 5,
    "seats": 7
}

### Eventuell noch zusätzlich
PATCH  http://localhost:3000/645e6e3c3bfb288684990525
Content-Type: application/json

{
     "rating": 2
}


###
DELETE http://localhost:3003/646e93876e6c3a9d361d1777