### alle Flüge
GET http://localhost:3002/all

### Flüge nach ID
GET http://localhost:3002/id/

### Flüge nach pricePerSeat
GET http://localhost:3002/pricePerSeat/

### Flüge nach start
GET http://localhost:3002/start/

### Flüge nach destination
GET http://localhost:3002/destination/

### Flüge nach flightTime
GET http://localhost:3002/flightTime/

### Flüge nach flightClass
GET http://localhost:3002/flightClass/

### Flüge nach departureTime
GET http://localhost:3002/departureTime/

### Flüge nach departureDate
GET http://localhost:3002/departureDate/

### Flüge nach arrivalTime
GET http://localhost:3002/arrivalTime/

### Flüge nach arrivalDate
GET http://localhost:3002/arrivalDate/

### Rating hinzufügen
POST http://localhost:3002/add 
Content-Type: application/json

{
    "pricePerSeat": 2500,
    "start": "Frankfurt",
    "destination": "Sydney",
    "flightTime": 20,
    "flightClass": "Economy",
    "departureTime": "13423423423",
    "departureDate": "168960",
    "arrivalTime": "23423434",
    "arrivalDate": "2342342342"
}


### Eintrag aktualisieren
PUT http://localhost:3002/
Content-Type: application/json

{
    "pricePerSeat": 0,
    "start": "",
    "destination": "",
    "flightTime": 0,
    "flightClass": "",
    "departureTime": "",
    "departureDate": "",
    "arrivalTime": "",
    "arrivalDate": ""
}

### Eventuell später
PATCH  http://localhost:3000/
Content-Type: application/json

{
     "rating": 2
}


### Eintrag löschen
DELETE http://localhost:3002/